
<?php
    require './plantillas/layouts/header.phtml';

    if(isset($fabrica)){
        echo '<h1>' . $fabrica->nombre . '</h1>';
        echo '<p>Pais: ' . $fabrica->pais . '</p>';
        echo '<p>Importador: ' . $fabrica->importador . '</p>';
        echo '<p>Cantidad: ' . $fabrica->cantidad . '</p>';
        echo '<a href=""/plantillas/lista_fabricas.phtml"' . '>Volver</a>';
    }
    
    require './plantillas/layouts/footer.phtml'
?>
<a href="/plantillas/lista_fabricas.phtml"></a>