<?php 
    require './plantillas/layouts/header.phtml';

        if(isset($fabricas)){
            echo '<ul>';
            foreach($fabricas as $fabrica){
                echo '<li>' . $fabrica->nombre . '</li>'; 
                echo '<a href="detallesfabrica/' . $fabrica->id . '">Ver mas</a>';
            }
            echo '</ul>';
        }
    
    require './plantillas/layouts/footer.phtml'
?>


